# Generated by Django 4.2.7 on 2024-02-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilemodel_delete_balancemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='borrowed_books',
        ),
    ]
