# Generated by Django 4.2.7 on 2024-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow_report',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
